name: Run Python Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check env variable
      run: echo Variable is $GOOGLE_APPLICATION_CREDENTIALS_CONTENT
      env:
        GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CONTENT }}

